-- Threads Activity → Follows attribution storage.
-- Raw observation states are append-only: the collector never updates or deletes rows.
-- Re-reading the same notification state is deduplicated per account.
-- If a grouped notification later changes (+5 → +20), the changed state is appended.

create table if not exists public.threads_activity_events (
    id bigint generated by default as identity primary key,
    account_key text not null,
    notification_id text not null,
    notification_datetime timestamptz,
    notification_type text not null default 'follow',
    visible_username text,
    source_snippet_raw text not null,
    source_snippet_normalized text not null,
    context_raw text,
    grouped_others_count integer not null default 0 check (grouped_others_count >= 0),
    follow_count integer not null default 1 check (follow_count >= 1),
    attribution_possible boolean not null default true,
    story_type text,
    matched_post_id text,
    matched_permalink text,
    match_method text,
    match_confidence text not null default 'unknown' check (
        match_confidence in ('high','medium','low','unknown')
    ),
    fallback_fingerprint text not null,
    collected_at timestamptz not null default now(),
    unique (account_key, fallback_fingerprint)
);

create index if not exists idx_threads_activity_events_notification
    on public.threads_activity_events (account_key, notification_id, collected_at desc);
create index if not exists idx_threads_activity_events_datetime
    on public.threads_activity_events (account_key, notification_datetime desc);
create index if not exists idx_threads_activity_events_post_confidence
    on public.threads_activity_events (account_key, matched_post_id, match_confidence);

alter table public.threads_activity_events enable row level security;
revoke all on table public.threads_activity_events from public, anon, authenticated;
revoke all on table public.threads_activity_events from service_role;
grant select, insert on table public.threads_activity_events to service_role;
grant usage, select on sequence public.threads_activity_events_id_seq to service_role;

comment on table public.threads_activity_events is
    'Append-only observations from Threads /activity/follows, isolated by operator account_key.';
comment on column public.threads_activity_events.matched_post_id is
    'Threads post ID from deterministic matching. No FK: owned posts may come directly from the official API.';

-- Rebuildable analytics: select the latest observed state for each account + notification,
-- then aggregate follow_count by account + matched source post. Medium confidence stays
-- explicitly separated because repeated-text attribution is inferred, not exact.
create or replace view public.threads_follows_from_post_summary
with (security_invoker = true) as
with latest_notification_state as (
    select distinct on (account_key, notification_id)
        account_key,
        notification_id,
        follow_count,
        matched_post_id,
        matched_permalink,
        match_confidence,
        collected_at
    from public.threads_activity_events
    order by account_key, notification_id, collected_at desc, id desc
)
select
    account_key,
    matched_post_id as post_id,
    max(matched_permalink) as permalink,
    coalesce(sum(follow_count) filter (where match_confidence = 'high'), 0)::bigint
        as high_confidence_follows,
    coalesce(sum(follow_count) filter (where match_confidence = 'medium'), 0)::bigint
        as medium_confidence_follows,
    coalesce(sum(follow_count) filter (where match_confidence = 'low'), 0)::bigint
        as low_confidence_follows,
    coalesce(sum(follow_count) filter (where match_confidence in ('high','medium')), 0)::bigint
        as follows_from_post_activity,
    count(*)::bigint as notification_rows,
    max(collected_at) as updated_at
from latest_notification_state
where matched_post_id is not null
group by account_key, matched_post_id;

revoke all on table public.threads_follows_from_post_summary from public, anon, authenticated;
grant select on table public.threads_follows_from_post_summary to service_role;
