-- Portable account-scoped queue for deterministic Threads publishing.
-- Live posting is separately gated by local account configuration.

create table if not exists public.threads_publish_queue (
    id bigint generated by default as identity primary key,
    account_key text not null,
    campaign_code text,
    main_post_text text not null check (length(btrim(main_post_text)) > 0),
    reply_texts jsonb not null default '[]'::jsonb check (jsonb_typeof(reply_texts) = 'array'),
    status text not null default 'draft' check (
        status in ('draft', 'approved', 'posting', 'posted', 'failed')
    ),
    scheduled_at timestamptz not null default now(),
    claimed_at timestamptz,
    threads_main_post_id text,
    threads_reply_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(threads_reply_ids) = 'array'),
    posted_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_threads_publish_queue_due
    on public.threads_publish_queue (account_key, status, scheduled_at, id);
create index if not exists idx_threads_publish_queue_campaign
    on public.threads_publish_queue (account_key, campaign_code, status, scheduled_at);

alter table public.threads_publish_queue enable row level security;
revoke all on table public.threads_publish_queue from public, anon, authenticated;
revoke all on table public.threads_publish_queue from service_role;
grant select, insert, update on table public.threads_publish_queue to service_role;
grant usage, select on sequence public.threads_publish_queue_id_seq to service_role;

comment on table public.threads_publish_queue is
    'Account-scoped operator queue. Workers must claim approved rows before publishing.';
