-- Account-scoped engagement queue with explicit human approval for replies.
-- Hermes may propose actions, but reply execution is impossible until status=approved.

create table if not exists public.threads_engagement_queue (
    id bigint generated by default as identity primary key,
    account_key text not null,
    trend_candidate_id bigint null references public.threads_trend_candidates(id) on delete set null,
    source_post_id text null,
    source_permalink text not null,
    source_username text null,
    source_text text null,
    action text not null check (action in ('reply','repost','like')),
    proposed_text text null,
    score numeric null check (score is null or (score >= 0 and score <= 100)),
    reason text null,
    status text not null default 'draft'
        check (status in (
            'draft','pending_approval','approved','executing',
            'posted','rejected','expired','failed','skipped'
        )),
    approval_channel text null,
    approval_ref text null,
    approved_at timestamptz null,
    rejected_at timestamptz null,
    expires_at timestamptz null,
    claimed_at timestamptz null,
    executed_at timestamptz null,
    external_action_id text null,
    last_error text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint threads_engagement_reply_text_check check (
        action <> 'reply' or proposed_text is not null
    ),
    constraint threads_engagement_source_id_check check (
        action = 'like' or source_post_id is not null
    ),
    constraint threads_engagement_approval_check check (
        action <> 'reply'
        or status in ('draft','pending_approval','rejected','expired','skipped','failed')
        or approved_at is not null
    )
);

create unique index if not exists threads_engagement_queue_action_dedupe_idx
    on public.threads_engagement_queue (account_key, source_permalink, action);

create index if not exists threads_engagement_queue_pending_idx
    on public.threads_engagement_queue (account_key, status, created_at);

create index if not exists threads_engagement_queue_candidate_idx
    on public.threads_engagement_queue (trend_candidate_id);

alter table public.threads_engagement_queue enable row level security;

revoke all on table public.threads_engagement_queue from public;
revoke all on table public.threads_engagement_queue from anon, authenticated;
grant select, insert, update on table public.threads_engagement_queue to service_role;
grant usage, select on sequence public.threads_engagement_queue_id_seq to service_role;

comment on table public.threads_engagement_queue is
'Account-scoped engagement actions. Replies require explicit human approval before execution.';
