-- Migration 010: two engagement workflows.
-- Workflow A (trend candidate -> original own post) reuses threads_trend_candidates;
-- this widens its status CHECK to the extended lifecycle. The old statuses remain
-- valid so existing rows are untouched.
-- Workflow B (replies under our own posts) gets a dedicated state table,
-- threads_own_reply_engagement, with the same approval-gate invariants as
-- threads_engagement_queue.

-- ---------------------------------------------------------------
-- 1) threads_trend_candidates: extended status lifecycle
--    old: discovered, reviewed, approved, rejected, used, stale
--    new adds: drafted, pending_approval, queued, skipped, posted, failed
-- ---------------------------------------------------------------
do $$
declare
    conname text;
begin
    select con.conname into conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where rel.relname = 'threads_trend_candidates'
      and nsp.nspname = 'public'
      and con.contype = 'check'
      and pg_get_constraintdef(con.oid) ilike '%status%';

    if conname is not null then
        execute format('alter table public.threads_trend_candidates drop constraint %I', conname);
    end if;
end $$;

alter table public.threads_trend_candidates
    add constraint threads_trend_candidates_status_check check (
        status in (
            'discovered', 'drafted', 'pending_approval', 'approved',
            'queued', 'rejected', 'skipped', 'posted', 'failed',
            'reviewed', 'used', 'stale'
        )
    );

-- One live queue row per trend candidate (Workflow A approve -> enqueue is
-- idempotent; a second approval of the same candidate is a no-op).
create unique index if not exists threads_trend_candidates_used_queue_uidx
    on public.threads_trend_candidates (used_in_queue_id)
    where used_in_queue_id is not null;

-- ---------------------------------------------------------------
-- 2) Workflow B: replies under our own posts
-- ---------------------------------------------------------------
create table if not exists public.threads_own_reply_engagement (
    id bigint generated by default as identity primary key,
    account_key text not null,
    -- Discovery identity (from the official Graph API /{post-id}/replies edge)
    reply_id text not null,                 -- Graph media id of the inbound reply
    parent_post_id text not null,           -- Graph media id of OUR post being replied to
    parent_post_permalink text null,
    parent_post_text text null,
    from_username text null,
    reply_text text null,
    reply_permalink text null,
    replied_at timestamptz null,
    -- Generated proposal
    proposed_text text null,
    -- State machine
    status text not null default 'discovered'
        check (status in (
            'discovered', 'pending_approval', 'approved', 'rejected',
            'ignored', 'posting', 'posted', 'failed'
        )),
    approval_channel text null,
    approval_ref text null,
    approved_at timestamptz null,
    rejected_at timestamptz null,
    ignored_at timestamptz null,
    claimed_at timestamptz null,
    executed_at timestamptz null,
    external_action_id text null,           -- Graph media id of OUR published reply
    last_error text null,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint threads_own_reply_approval_check check (
        status in ('discovered','pending_approval','rejected','ignored','failed')
        or approved_at is not null
    ),
    constraint threads_own_reply_proposed_text_check check (
        status = 'discovered' or proposed_text is not null
    )
);

-- Deduplicate by the Graph reply id per account: one inbound reply is only
-- ever proposed once, regardless of how many watchdog ticks see it.
create unique index if not exists threads_own_reply_engagement_dedupe_uidx
    on public.threads_own_reply_engagement (account_key, reply_id);

create index if not exists threads_own_reply_engagement_status_idx
    on public.threads_own_reply_engagement (account_key, status, created_at);

comment on table public.threads_own_reply_engagement is
    'Approval-gated responses to replies under our own Threads posts (Workflow B). '
    'Nothing publishes until status transitions pending_approval -> approved via Telebot.';
