-- Migration 013: reconcile MISSING base tables into repository migrations (Part 5).
--
-- These tables exist in production Supabase (project ztoxaksrdbcgceyulzwm) but
-- were created by ad-hoc SQL Editor statements that were never captured as
-- repository migrations. A fresh Supabase project could therefore NOT reach the
-- production schema using migrations/001..012 alone.
--
-- Live schema was introspected 2026-09-23 via the PostgREST OpenAPI document
-- (GET /rest/v1/ with the service role) — the ONLY schema source available
-- programmatically (no postgres connection string, no Supabase CLI, no DDL
-- API). Column types/defaults below mirror production exactly.
--
-- ADDITIVE ONLY + idempotent. Safe to run on the existing production database:
--   * create table if not exists / add column if not exists — no-ops where live.
--   * Constraints are added via DO blocks that skip when a constraint of the
--     same name already exists (production may already carry equivalents).
--   * Tiada DROP, tiada ALTER pada table sedia ada besides ADD CONSTRAINT.
--
-- Ordering note: on a FRESH database, apply THIS FILE BEFORE 010/011/012,
-- because those migrations ALTER threads_trend_candidates which no earlier
-- migration creates (the gap this file closes). Division of labour on the
-- trend table: 013 creates the table; 010 owns the status lifecycle CHECK;
-- 011 owns the used_in_queue_id FK; 012 adds approval_sent_at/timed_out_at +
-- the backlog statuses/indexes. On the EXISTING production database this file
-- is a no-op for the trend table (IF NOT EXISTS + guarded grants).
--
-- Honesty caveats from introspection limits (OpenAPI reveals columns, types,
-- defaults, PKs and FKs — nothing else):
--   * id "generated by default as identity" reproduces a bigint PK with a
--     sequence; whether production uses identity vs bigserial is not visible
--     via OpenAPI. Functionally equivalent for all code paths (id is never
--     client-supplied).
--   * Secondary indexes and unique constraints beyond PKs are NOT reproduced
--     (not introspectable), except where 010/011/012 define them.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1) threads_trend_candidates — trend discovery + Workflow A lifecycle.
--    (status CHECK added by 010; used_in_queue_id FK bigint added by 011;
--     approval_sent_at/timed_out_at + backlog indexes added by 012.)
-- ---------------------------------------------------------------------------
create table if not exists public.threads_trend_candidates (
    id                       bigint generated by default as identity primary key,
    target_account_id        text not null,
    source_platform          text not null default 'threads',
    source_post_id           text null,
    source_username          text null,
    source_permalink         text not null,
    source_text              text null,
    source_language          text null,
    published_at             timestamptz null,
    discovered_at            timestamptz not null default now(),
    last_checked_at          timestamptz null,
    topic                    text null,
    content_category         text null,
    content_format           text null,
    hook_type                text null,
    tone                     text null,
    keywords                 text[] not null,
    source_followers_count   bigint null,
    views                    bigint null,
    likes                    bigint null,
    replies                  bigint null,
    reposts                  bigint null,
    quotes                   bigint null,
    engagement_total         bigint null,
    engagement_rate          numeric null,
    age_hours                numeric null,
    velocity_score           numeric null,
    trend_score              numeric null,
    why_it_works             text null,
    adaptation_angle         text null,
    status                   text not null default 'discovered',
    used_in_queue_id         bigint null,
    first_seen_metrics       jsonb not null,
    latest_metrics           jsonb not null,
    raw_metadata             jsonb not null,
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now()
);

-- NOTE: secondary indexes on this table are intentionally NOT recreated here —
-- OpenAPI introspection cannot see them, and inventing unverified index
-- definitions would be dishonest. 010/012 add the indexes the workflows
-- actually need (used_queue_uidx, pending_approval_at, backlog_account).

comment on table public.threads_trend_candidates is
    'External trend posts discovered for engagement (Workflow A source pool). '
    'Lifecycle owned by migrations 010-012; ingestion via Hermes trend-discovery skill.';

-- ---------------------------------------------------------------------------
-- 2) threads_engagement_config — engagement policy per config_key.
-- ---------------------------------------------------------------------------
create table if not exists public.threads_engagement_config (
    config_key                        text primary key default 'default',
    enabled                           boolean not null default true,
    min_replies_per_day               integer not null default 20,
    target_replies_per_day            integer not null default 25,
    max_replies_per_day               integer not null default 30,
    min_reply_words                   integer not null default 3,
    max_reply_words                   integer not null default 15,
    preferred_recency_hours           integer not null default 24,
    max_replies_per_account_per_day   integer not null default 1,
    topics                            jsonb not null,
    blocked_topics                    jsonb not null,
    preferred_languages               jsonb not null,
    reply_windows                     jsonb not null,
    test_started_at                   timestamptz null,
    test_ends_at                      timestamptz null,
    notes                             text null,
    created_at                        timestamptz not null default now(),
    updated_at                        timestamptz not null default now()
);

comment on table public.threads_engagement_config is
    'Engagement policy knobs (reply quotas, topics, windows). Read by the '
    'engagement tooling; single "default" row in production as of 2026-09-23.';

-- ---------------------------------------------------------------------------
-- 3) threads_gateway_keys — hashed API keys for the Threads gateway.
--    Key MATERIAL never lives here (hash only), so this table is safe to
--    manage via migrations. Not referenced by this repo's code — used by the
--    external gateway; creation is reconciled for schema reproducibility.
-- ---------------------------------------------------------------------------
create table if not exists public.threads_gateway_keys (
    id           uuid primary key default gen_random_uuid(),
    key_name     text not null,
    key_hash     text not null,
    enabled      boolean not null default true,
    permissions  jsonb not null,
    expires_at   timestamptz null,
    last_used_at timestamptz null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

-- Non-unique: OpenAPI introspection does not reveal unique constraints, so we
-- only index key_name without asserting uniqueness (production may or may not
-- enforce it; matching column set/types is what matters for a fresh install).
create index if not exists threads_gateway_keys_key_name_idx
    on public.threads_gateway_keys (key_name);

comment on table public.threads_gateway_keys is
    'Gateway auth key registry (hashes only, never raw keys). Owned by the '
    'external Threads gateway, not threads-operator code.';

-- ---------------------------------------------------------------------------
-- 4) threads_posts — master registry of own published posts. REQUIRED by
--    current behaviour: supabase_store.list_posts() feeds activity attribution
--    (activity_collector) and the insights/enrichment read paths. Created
--    historically by the legacy social-automation stack, never captured here.
-- ---------------------------------------------------------------------------
create table if not exists public.threads_posts (
    thread_id                text primary key,
    username                 text null,
    permalink                text null,
    text                     text null,
    media_type               text null,
    published_at             timestamptz null,
    category                 text null,
    topic_tag                text not null,
    is_reply                 boolean not null default false,
    is_quote_post            boolean not null default false,
    root_post_id             text null,
    replied_to_id            text null,
    source_table             text null,
    source_row_id            text null,
    first_seen_at            timestamptz not null default now(),
    last_seen_at             timestamptz not null default now(),
    latest_views             bigint not null default 0,
    latest_likes             bigint not null default 0,
    latest_api_replies       bigint not null default 0,
    latest_own_replies       integer not null default 0,
    latest_external_replies  integer not null default 0,
    latest_reposts           bigint not null default 0,
    latest_quotes            bigint not null default 0,
    latest_public_engagement bigint not null default 0,
    latest_metrics_at        timestamptz null,
    raw_media                jsonb not null,
    updated_at               timestamptz not null default now()
);

comment on table public.threads_posts is
    'Master registry of our published Threads posts + latest metrics; read by '
    'activity attribution and insight enrichment. Written by the legacy browser '
    'sync stack; operator code reads thread_id/text/published_at/permalink.';

-- ---------------------------------------------------------------------------
-- 5) threads_inbound_replies — replies from others under our posts (legacy
--    browser sync; FK to threads_posts). Required for fresh installs that run
--    the legacy enrichment path; harmless otherwise.
-- ---------------------------------------------------------------------------
create table if not exists public.threads_inbound_replies (
    reply_id          text primary key,
    parent_thread_id  text null references public.threads_posts(thread_id),
    root_thread_id    text null,
    replied_to_id     text null,
    username          text not null,
    text              text null,
    permalink         text null,
    replied_at        timestamptz null,
    is_owned_by_me    boolean not null default false,
    first_seen_at     timestamptz not null default now(),
    last_seen_at      timestamptz not null default now(),
    raw_media         jsonb not null,
    updated_at        timestamptz not null default now()
);

create table if not exists public.threads_post_metric_snapshots (
    id                 uuid primary key default gen_random_uuid(),
    thread_id          text not null references public.threads_posts(thread_id),
    captured_at        timestamptz not null default now(),
    views              bigint not null default 0,
    likes              bigint not null default 0,
    api_replies        bigint not null default 0,
    own_replies        integer not null default 0,
    external_replies   integer not null default 0,
    reposts            bigint not null default 0,
    quotes             bigint not null default 0,
    public_engagement  bigint not null default 0,
    raw_payload        jsonb not null,
    created_at         timestamptz not null default now()
);

comment on table public.threads_inbound_replies is
    'Legacy browser-sync registry of inbound replies under our posts. FK: '
    'parent_thread_id -> threads_posts.thread_id (verified via OpenAPI).';
comment on table public.threads_post_metric_snapshots is
    'Legacy browser-sync per-post metric snapshots (superseded for the '
    'operator by threads_post_insights_snapshots, migration 001b).';

-- NOT reconciled here (intentional external dependencies, legacy stack, no
-- operator-code writes): threads_content_queue (legacy scheduler queue;
-- topic.py maps it defensively only), threads_outbound_replies, threads_leads
-- (affiliate/lead pipeline). Documented in docs/repo-reconciliation.md Part 5.

-- Grants follow the 006 security-hardening pattern: client roles stay out.
revoke all on table public.threads_trend_candidates from public;
revoke all on table public.threads_trend_candidates from anon, authenticated;
grant select, insert, update, delete on table public.threads_trend_candidates to service_role;

revoke all on table public.threads_engagement_config from public;
revoke all on table public.threads_engagement_config from anon, authenticated;
grant select, insert, update on table public.threads_engagement_config to service_role;

revoke all on table public.threads_gateway_keys from public;
revoke all on table public.threads_gateway_keys from anon, authenticated;
grant select, insert, update, delete on table public.threads_gateway_keys to service_role;

revoke all on table public.threads_posts from public;
revoke all on table public.threads_posts from anon, authenticated;
grant select, insert, update on table public.threads_posts to service_role;

revoke all on table public.threads_inbound_replies from public;
revoke all on table public.threads_inbound_replies from anon, authenticated;
grant select, insert, update on table public.threads_inbound_replies to service_role;

revoke all on table public.threads_post_metric_snapshots from public;
revoke all on table public.threads_post_metric_snapshots from anon, authenticated;
grant select, insert on table public.threads_post_metric_snapshots to service_role;
