-- Migration 015: context engine + intent classification for Workflow B.
--
-- Adds deterministic context and intent classification fields to
-- threads_own_reply_engagement so the operator can assemble structured
-- context before Hermes drafts a response, and classify reply intent to
-- decide CTA/lead outcomes.
--
-- No LLM provider/API key is added to the operator. The operator collects
-- and stores deterministic context; Hermes consumes it for interpretation.

-- ---------------------------------------------------------------------------
-- 1) threads_own_reply_engagement: context + intent fields
-- ---------------------------------------------------------------------------

alter table public.threads_own_reply_engagement
    add column if not exists context_json jsonb null,
    add column if not exists intent text null,
    add column if not exists intent_evidence jsonb null,
    add column if not exists lead_score numeric null
        check (lead_score is null or (lead_score >= 0 and lead_score <= 1)),
    add column if not exists dm_opportunity_id bigint null,
    add column if not exists classified_at timestamptz null;

comment on column public.threads_own_reply_engagement.context_json is
    'Deterministic context assembled at classification time: account, root post, parent reply, conversation chain, topic, pillar, objective, CTA, persona, prior interactions. Bounded — no unlimited history.';
comment on column public.threads_own_reply_engagement.intent is
    'Classified intent: casual, question, positive_engagement, objection, buying_intent, cta_match, potential_lead, needs_human_review.';
comment on column public.threads_own_reply_engagement.intent_evidence is
    'Deterministic evidence used for classification (keyword matches, CTA patterns, contextual signals).';
comment on column public.threads_own_reply_engagement.lead_score is
    '0.0-1.0 confidence that this reply represents a lead/DM opportunity. NULL when not classified.';
comment on column public.threads_own_reply_engagement.dm_opportunity_id is
    'FK to threads_dm_opportunities when this reply generated a DM opportunity.';
comment on column public.threads_own_reply_engagement.classified_at is
    'When intent classification was performed.';

-- ---------------------------------------------------------------------------
-- 2) threads_dm_opportunities: DM opportunity state machine
-- ---------------------------------------------------------------------------

create table if not exists public.threads_dm_opportunities (
    id bigint generated by default as identity primary key,
    account_key text not null,
    -- Source identity
    source_reply_id text not null,           -- Graph media id of the inbound reply
    source_own_reply_id bigint not null
        references public.threads_own_reply_engagement(id) on delete cascade,
    from_username text not null,
    -- Context (denormalized for fast access without joins)
    root_post_id text not null,
    root_post_permalink text null,
    root_post_text text null,
    reply_text text null,
    reply_permalink text null,
    cta_matched text null,                   -- The CTA pattern that matched (e.g. "berminat")
    intent text not null,
    lead_score numeric not null
        check (lead_score >= 0 and lead_score <= 1),
    -- DM content (populated by Hermes in Task #2 continuation)
    dm_draft_text text null,
    dm_approved_text text null,
    -- State machine
    status text not null default 'detected'
        check (status in (
            'detected', 'drafted', 'awaiting_approval', 'approved',
            'sending', 'sent', 'rejected', 'failed', 'expired', 'cancelled'
        )),
    approval_channel text null,
    approval_ref text null,
    approved_at timestamptz null,
    rejected_at timestamptz null,
    expired_at timestamptz null,
    cancelled_at timestamptz null,
    claimed_at timestamptz null,
    sent_at timestamptz null,
    external_dm_id text null,               -- Graph DM id once sent
    last_error text null,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    -- Dedup: one active DM opportunity per (account, user, root_post)
    constraint threads_dm_opportunities_dedupe_uidx
        unique (account_key, from_username, root_post_id)
);

comment on table public.threads_dm_opportunities is
    'DM opportunities detected from own-post replies. Lifecycle: detected -> drafted -> awaiting_approval -> approved -> sending -> sent. Terminal: rejected/failed/expired/cancelled.';

-- Indexes for common query patterns
create index if not exists threads_dm_opportunities_status_idx
    on public.threads_dm_opportunities (account_key, status, created_at);

create index if not exists threads_dm_opportunities_source_reply_idx
    on public.threads_dm_opportunities (source_reply_id);

create index if not exists threads_dm_opportunities_from_username_idx
    on public.threads_dm_opportunities (account_key, from_username);

-- RLS: service_role only, same pattern as other operator tables
alter table public.threads_dm_opportunities enable row level security;

revoke all on table public.threads_dm_opportunities from public;
revoke all on table public.threads_dm_opportunities from anon, authenticated;
grant select, insert, update on table public.threads_dm_opportunities to service_role;
grant usage, select on sequence public.threads_dm_opportunities_id_seq to service_role;

drop policy if exists "service_role_all_threads_dm_opportunities" on public.threads_dm_opportunities;
create policy "service_role_all_threads_dm_opportunities"
    on public.threads_dm_opportunities for all to service_role using (true) with check (true);

-- ---------------------------------------------------------------------------
-- 3) threads_own_reply_engagement: add FK to dm_opportunities
-- ---------------------------------------------------------------------------

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'threads_own_reply_engagement_dm_opportunity_fkey'
    ) then
        alter table public.threads_own_reply_engagement
            add constraint threads_own_reply_engagement_dm_opportunity_fkey
            foreign key (dm_opportunity_id)
            references public.threads_dm_opportunities(id)
            on delete set null;
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4) threads_posts: ensure topic_tag and category are accessible for context
-- ---------------------------------------------------------------------------
-- The threads_posts table already has topic_tag and category from migration 013.
-- No schema change needed — the context engine reads from it directly.

-- ---------------------------------------------------------------------------
-- 5) threads_engagement_config: add CTA patterns for deterministic matching
-- ---------------------------------------------------------------------------

alter table public.threads_engagement_config
    add column if not exists cta_patterns jsonb not null default '[]'::jsonb;

comment on column public.threads_engagement_config.cta_patterns is
    'JSON array of CTA patterns for deterministic matching, e.g. ["berminat", "nak", "dm saya", "pm", "link please"]. Used by the intent classifier to detect CTA matches without LLM.';
